foreground         #FEF3E9
background         #19191C
background_opacity 
cursor             #DCBA8D

active_tab_foreground     #FEF3E9
active_tab_background     #19191C
inactive_tab_foreground   #FEF3E9
inactive_tab_background   #19191C

active_border_color   #FEF3E9
inactive_border_color #19191C
bell_border_color     #916152

color0       #434347
color8       #ABA097
color1       #916152
color9       #916152
color2       #BA7A1F
color10      #BA7A1F
color3       #7666AF
color11      #7666AF
color4       #58B256
color12      #58B256
color5       #1AAEF1
color13      #1AAEF1
color6       #FBB87D
color14      #FBB87D
color7       #F4E5D8
color15      #F4E5D8
