[colors.primary]
background = "#19191C"
foreground = "#FEF3E9"

[colors.cursor]
text = "#916152"
cursor = "#FEF3E9"

[colors.vi_mode_cursor]
text = "#19191C"
cursor = "#FEF3E9"

[colors.search.matches]
foreground = "#434347"
background = "#F4E5D8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#ABA097"
background = "#F4E5D8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black ="#434347" 
red = "#916152"
green = "#BA7A1F"
yellow = "#7666AF"
blue = "#58B256"
magenta = "#1AAEF1"
cyan = "#FBB87D"
white = "#F4E5D8"

[colors.bright]
black = "#ABA097"
red = "#916152"
green = "#BA7A1F"
yellow = "#7666AF"
blue = "#58B256"
magenta = "#1AAEF1"
cyan = "#FBB87D"
white = "#F4E5D8"

[colors.dim]
black = "#916152"
red = "#916152"
green = "#1AAEF1"
yellow = "#7666AF"
blue = "#58B256"
magenta = "#BA7A1F"
cyan = "#FBB87D"
white = "#ABA097"

